export type CropId = 'carrot' | 'potato' | 'wheat' | 'tomato' | 'raspberry' | 'watermelon' | 'apple'

export type TileId = 'paved' | 'brick' | 'cobble'

export type StallGoodId = CropId | 'berry'

export type ShovelId = 'shovel' | 'better-shovel'

export type PickaxeId = 'pickaxe' | 'better-pickaxe'

export type ContainerId = 'bucket' | 'large-bucket'

export type ResearchId =
  | 'unlock-tomato'
  | 'unlock-raspberry'
  | 'unlock-watermelon'
  | 'bump-carrot'
  | 'bump-potato'
  | 'bump-wheat'
  | 'unlock-better-tools'
  | 'unlock-large-box'
  | 'unlock-irrigation'
  | 'unlock-auto-irrigation'
  | 'unlock-adv-irrigation'
  | 'unlock-expand'
  | 'unlock-pickaxe'
  | 'unlock-chest'
  | 'unlock-grinder'
  | 'unlock-fertilizer'
  | 'unlock-compost'

export type SkuId =
  | 'pack-carrot'
  | 'pack-potato'
  | 'pack-wheat'
  | 'pack-tomato'
  | 'pack-raspberry'
  | 'pack-watermelon'
  | 'buy-shovel'
  | 'buy-better-shovel'
  | 'buy-pickaxe'
  | 'buy-better-pickaxe'
  | 'buy-bucket'
  | 'buy-bucket-large'
  | 'buy-box'
  | 'buy-box-large'
  | 'buy-fertilizer'
  | 'buy-synth-fertilizer'
  | 'buy-compost-box'
  | 'buy-pumpjack'
  | 'buy-chest'
  | 'buy-grinder'
  | 'buy-pipe'
  | 'buy-sprinkler'
  | 'buy-sprinkler-vert'
  | 'buy-sprinkler-large'
  | 'buy-well'
  | 'buy-tile-paved'
  | 'buy-tile-brick'
  | 'buy-tile-cobble'
