export type CropId = 'carrot' | 'potato' | 'wheat' | 'tomato' | 'raspberry' | 'watermelon' | 'apple'

export type TileId = 'paved' | 'brick' | 'cobble'

export type StallGoodId = CropId | 'berry'

export type ShovelId = 'shovel' | 'better-shovel' | 'rotary-shovel'

export type PickaxeId = 'pickaxe' | 'better-pickaxe' | 'diamond-pickaxe'

export type ContainerId = 'bucket' | 'large-bucket'

export type MemberId = 'player' | 'husband' | 'daughter'

export type PlayerSkillId =
  | 'boots'
  | 'machinery'
  | 'tending'
  | 'seed-bank'
  | 'better-carrot'
  | 'better-potato'
  | 'better-wheat'
  | 'better-tomato'
  | 'better-raspberry'
  | 'better-watermelon'

export type HusbandSkillId =
  | 'research-speed'
  | 'tool-contracts'
  | 'machine-contracts'
  | 'forecast'
  | 'tax'
  | 'water-study'
  | 'land-study'
  | 'bulk-buying'

export type DaughterSkillId =
  | 'saleswoman'
  | 'heirloom'
  | 'bio'
  | 'industrial'
  | 'open-late'
  | 'open-24'
  | 'jam'
  | 'clearance'

export type SkillId = PlayerSkillId | HusbandSkillId | DaughterSkillId

export type ResearchId =
  | 'unlock-tomato'
  | 'unlock-raspberry'
  | 'unlock-watermelon'
  | 'unlock-heirloom'
  | 'unlock-better-tools'
  | 'unlock-large-box'
  | 'unlock-irrigation'
  | 'unlock-auto-irrigation'
  | 'unlock-adv-irrigation'
  | 'unlock-expand'
  | 'unlock-pickaxe'
  | 'unlock-chest'
  | 'unlock-grinder'
  | 'unlock-fertilizer'
  | 'unlock-compost'
  | 'unlock-smart-sprinkler'
  | 'unlock-landscaping'
  | 'unlock-rotary-shovel'
  | 'unlock-diamond-pickaxe'

export type SkuId =
  | 'pack-carrot'
  | 'pack-potato'
  | 'pack-wheat'
  | 'pack-tomato'
  | 'pack-raspberry'
  | 'pack-watermelon'
  | 'buy-shovel'
  | 'buy-better-shovel'
  | 'buy-pickaxe'
  | 'buy-better-pickaxe'
  | 'buy-bucket'
  | 'buy-bucket-large'
  | 'buy-box'
  | 'buy-box-large'
  | 'buy-fertilizer'
  | 'buy-synth-fertilizer'
  | 'buy-compost-box'
  | 'buy-pumpjack'
  | 'buy-chest'
  | 'buy-grinder'
  | 'buy-pipe'
  | 'buy-sprinkler'
  | 'buy-sprinkler-vert'
  | 'buy-sprinkler-large'
  | 'buy-well'
  | 'buy-valve'
  | 'buy-rain-tank'
  | 'buy-tap'
  | 'buy-tile-paved'
  | 'buy-tile-brick'
  | 'buy-tile-cobble'
  | 'buy-fence'
  | 'pack-grass'
  | 'buy-rotary-shovel'
  | 'buy-diamond-pickaxe'
