import {DIAMOND_MINES, ROTARY_DIGS} from './items.ts'
import type {ResearchId, SkuId} from '../sim/ids.ts'

export type ResearchGate = { kind: 'none' } | { kind: 'digs'; n: number } | { kind: 'mines'; n: number }

export type ResearchDef = {
    id: ResearchId
    name: string
    tree: 'plants' | 'utilities' | 'expansion' | 'automation'
    cost: number
    seconds: number
    reveal: 'start' | ResearchId
    gate: ResearchGate
    blurb: string
    effect:
        | { kind: 'unlock-sku'; sku: SkuId }
        | { kind: 'expand' }
        | { kind: 'feature' }
}

export const RESEARCH: { readonly [K in ResearchId]: ResearchDef } = {
    'unlock-tomato': {
        id: 'unlock-tomato',
        name: 'Tomato seeds',
        tree: 'plants',
        cost: 7,
        seconds: 30,
        reveal: 'start',
        gate: {kind: 'none'},
        blurb: 'Unlocks Tomato seeds in the general store.',
        effect: {kind: 'unlock-sku', sku: 'pack-tomato'},
    },
    'unlock-olive': {
        id: 'unlock-olive',
        name: 'Olive seeds',
        tree: 'plants',
        cost: 11,
        seconds: 42,
        reveal: 'unlock-tomato',
        gate: {kind: 'none'},
        blurb: 'Unlocks Olive seeds in the general store.',
        effect: {kind: 'unlock-sku', sku: 'pack-olive'},
    },
    'unlock-grape': {
        id: 'unlock-grape',
        name: 'Grape seeds',
        tree: 'plants',
        cost: 10,
        seconds: 40,
        reveal: 'start',
        gate: {kind: 'none'},
        blurb: 'Unlocks Grape seeds in the general store.',
        effect: {kind: 'unlock-sku', sku: 'pack-grape'},
    },
    'unlock-raspberry': {
        id: 'unlock-raspberry',
        name: 'Raspberry seeds',
        tree: 'plants',
        cost: 12,
        seconds: 45,
        reveal: 'unlock-grape',
        gate: {kind: 'none'},
        blurb: 'Unlocks Raspberry seeds in the general store.',
        effect: {kind: 'unlock-sku', sku: 'pack-raspberry'},
    },
    'unlock-watermelon': {
        id: 'unlock-watermelon',
        name: 'Watermelon seeds',
        tree: 'plants',
        cost: 8,
        seconds: 35,
        reveal: 'start',
        gate: {kind: 'none'},
        blurb: 'Unlocks Watermelon seeds in the general store.',
        effect: {kind: 'unlock-sku', sku: 'pack-watermelon'},
    },
    'unlock-heirloom': {
        id: 'unlock-heirloom',
        name: 'Heirloom crops',
        tree: 'plants',
        cost: 20,
        seconds: 120,
        reveal: 'start',
        gate: {kind: 'none'},
        blurb: 'Unlocks Őstermelő. Heirloom produce can sell for more.',
        effect: {kind: 'feature'},
    },
    'unlock-better-tools': {
        id: 'unlock-better-tools',
        name: 'Better gardening tools',
        tree: 'utilities',
        cost: 16,
        seconds: 45,
        reveal: 'start',
        gate: {kind: 'none'},
        blurb: 'Unlocks Better shovel and Large bucket in the general store.',
        effect: {kind: 'unlock-sku', sku: 'buy-better-shovel'},
    },
    'unlock-large-box': {
        id: 'unlock-large-box',
        name: 'Fruit boxes',
        tree: 'utilities',
        cost: 17,
        seconds: 50,
        reveal: 'start',
        gate: {kind: 'none'},
        blurb: 'Unlocks Large fruit box in the general store.',
        effect: {kind: 'unlock-sku', sku: 'buy-box-large'},
    },
    'unlock-irrigation': {
        id: 'unlock-irrigation',
        name: 'Irrigation',
        tree: 'automation',
        cost: 20,
        seconds: 50,
        reveal: 'start',
        gate: {kind: 'none'},
        blurb: 'Unlocks Pumpjack in the general store.',
        effect: {kind: 'unlock-sku', sku: 'buy-pumpjack'},
    },
    'unlock-vehicles': {
        id: 'unlock-vehicles',
        name: 'Vehicles',
        tree: 'automation',
        cost: 32,
        seconds: 70,
        reveal: 'unlock-irrigation',
        gate: {kind: 'none'},
        blurb: 'Unlocks Hangar, tractor, trailers, and field silos. Buy Quads and tractors at a hangar.',
        effect: {kind: 'unlock-sku', sku: 'buy-hangar'},
    },
    'unlock-auto-irrigation': {
        id: 'unlock-auto-irrigation',
        name: 'Automated irrigation',
        tree: 'automation',
        cost: 22,
        seconds: 55,
        reveal: 'unlock-irrigation',
        gate: {kind: 'none'},
        blurb: 'Unlocks Pipe, Sprinkler, Manual valve, Rainwater tank and Tap in the general store.',
        effect: {kind: 'unlock-sku', sku: 'buy-pipe'},
    },
    'unlock-adv-irrigation': {
        id: 'unlock-adv-irrigation',
        name: 'Advanced irrigation',
        tree: 'automation',
        cost: 28,
        seconds: 65,
        reveal: 'unlock-auto-irrigation',
        gate: {kind: 'none'},
        blurb: 'Unlocks Well, Vertical sprinkler, and Large sprinkler in the general store.',
        effect: {kind: 'unlock-sku', sku: 'buy-well'},
    },
    'unlock-smart-sprinkler': {
        id: 'unlock-smart-sprinkler',
        name: 'Smart sprinklers',
        tree: 'automation',
        cost: 30,
        seconds: 70,
        reveal: 'unlock-adv-irrigation',
        gate: {kind: 'none'},
        blurb: 'Every sprinkler gains a crop dial. Tuned to a crop, it pours exactly what that crop drinks.',
        effect: {kind: 'feature'},
    },
    'unlock-chest': {
        id: 'unlock-chest',
        name: 'Chest',
        tree: 'utilities',
        cost: 12,
        seconds: 40,
        reveal: 'start',
        gate: {kind: 'none'},
        blurb: 'Unlocks Chest in the general store.',
        effect: {kind: 'unlock-sku', sku: 'buy-chest'},
    },
    'unlock-expand': {
        id: 'unlock-expand',
        name: 'Unlock land',
        tree: 'expansion',
        cost: 15,
        seconds: 45,
        reveal: 'start',
        gate: {kind: 'none'},
        blurb: 'Unlocks land expansion on the map edge.',
        effect: {kind: 'expand'},
    },
    'unlock-pickaxe': {
        id: 'unlock-pickaxe',
        name: 'Pickaxes',
        tree: 'utilities',
        cost: 0,
        seconds: 40,
        reveal: 'start',
        gate: {kind: 'none'},
        blurb: 'Unlocks Pickaxe and Hardened pickaxe in the general store.',
        effect: {kind: 'unlock-sku', sku: 'buy-pickaxe'},
    },
    'unlock-fertilizer': {
        id: 'unlock-fertilizer',
        name: 'Fertilizer',
        tree: 'plants',
        cost: 9,
        seconds: 40,
        reveal: 'start',
        gate: {kind: 'none'},
        blurb: 'Unlocks Synthetic fertilizer in the general store.',
        effect: {kind: 'unlock-sku', sku: 'buy-synth-fertilizer'},
    },
    'unlock-compost': {
        id: 'unlock-compost',
        name: 'Composting',
        tree: 'utilities',
        cost: 14,
        seconds: 45,
        reveal: 'unlock-fertilizer',
        gate: {kind: 'none'},
        blurb: 'Unlocks Compost box in the general store. Turns organic waste back into fertilizer.',
        effect: {kind: 'unlock-sku', sku: 'buy-compost-box'},
    },
    'unlock-grinder': {
        id: 'unlock-grinder',
        name: 'Seed grinder',
        tree: 'automation',
        cost: 18,
        seconds: 50,
        reveal: 'start',
        gate: {kind: 'none'},
        blurb: 'Unlocks Seed grinder and Mill in the general store.',
        effect: {kind: 'unlock-sku', sku: 'buy-grinder'},
    },
    'unlock-preservatives': {
        id: 'unlock-preservatives',
        name: 'Preservatives',
        tree: 'automation',
        cost: 20,
        seconds: 55,
        reveal: 'unlock-grinder',
        gate: {kind: 'none'},
        blurb: 'Unlocks Jam machine, Freezer, and Sugar in the general store.',
        effect: {kind: 'unlock-sku', sku: 'buy-jam'},
    },
    'unlock-fermentation': {
        id: 'unlock-fermentation',
        name: 'Fermentation',
        tree: 'automation',
        cost: 14,
        seconds: 50,
        reveal: 'start',
        gate: {kind: 'none'},
        blurb: 'Unlocks Sugar cane seeds, Pot still, and Wine barrel. Ripe cane is fruit. Mill cane for sugar.',
        effect: {kind: 'unlock-sku', sku: 'pack-sugar-cane'},
    },
    'unlock-landscaping': {
        id: 'unlock-landscaping',
        name: 'Landscape architecture',
        tree: 'expansion',
        cost: 12,
        seconds: 60,
        reveal: 'start',
        gate: {kind: 'none'},
        blurb: 'Unlocks Grass seeds, Wooden fence and every paving tile in the general store.',
        effect: {kind: 'unlock-sku', sku: 'pack-grass'},
    },
    'unlock-rotary-shovel': {
        id: 'unlock-rotary-shovel',
        name: 'Rotary shovel',
        tree: 'utilities',
        cost: 40,
        seconds: 120,
        reveal: 'unlock-better-tools',
        gate: {kind: 'digs', n: ROTARY_DIGS},
        blurb: 'Unlocks the Rotary shovel in the general store. Earned by digging, not by reading.',
        effect: {kind: 'unlock-sku', sku: 'buy-rotary-shovel'},
    },
    'unlock-diamond-pickaxe': {
        id: 'unlock-diamond-pickaxe',
        name: 'Diamond pickaxe',
        tree: 'utilities',
        cost: 40,
        seconds: 120,
        reveal: 'unlock-pickaxe',
        gate: {kind: 'mines', n: DIAMOND_MINES},
        blurb: 'Unlocks the Diamond pickaxe in the general store. Earned by mining, not by reading.',
        effect: {kind: 'unlock-sku', sku: 'buy-diamond-pickaxe'},
    },
}

export const GATE_TEXT: { readonly [K in ResearchGate['kind']]: string } = {
    none: '',
    digs: 'Dig ${have} / ${n} times to unlock this research.',
    mines: 'Mine ${have} / ${n} times to unlock this research.',
}

export type SkuTab = 'seeds' | 'utility' | 'automation' | 'building'

export type Sku = {
    id: SkuId
    price: number
    tab: SkuTab
    unlock: 'start' | ResearchId
    show: 'start' | ResearchId
    need?: 'vanilla-tending'
}

export const SKUS: { readonly [K in SkuId]: Sku } = {
    'pack-carrot': {id: 'pack-carrot', price: 3, tab: 'seeds', unlock: 'start', show: 'start'},
    'pack-potato': {id: 'pack-potato', price: 6, tab: 'seeds', unlock: 'start', show: 'start'},
    'pack-wheat': {id: 'pack-wheat', price: 10, tab: 'seeds', unlock: 'start', show: 'start'},
    'pack-tomato': {id: 'pack-tomato', price: 15, tab: 'seeds', unlock: 'unlock-tomato', show: 'start'},
    'pack-watermelon': {id: 'pack-watermelon', price: 18, tab: 'seeds', unlock: 'unlock-watermelon', show: 'start'},
    'pack-olive': {id: 'pack-olive', price: 14, tab: 'seeds', unlock: 'unlock-olive', show: 'unlock-tomato'},
    'pack-grape': {id: 'pack-grape', price: 16, tab: 'seeds', unlock: 'unlock-grape', show: 'start'},
    'pack-raspberry': {id: 'pack-raspberry', price: 22, tab: 'seeds', unlock: 'unlock-raspberry', show: 'unlock-grape'},
    'pack-vanilla': {
        id: 'pack-vanilla',
        price: 40,
        tab: 'seeds',
        unlock: 'start',
        show: 'unlock-raspberry',
        need: 'vanilla-tending',
    },
    'pack-sugar-cane': {id: 'pack-sugar-cane', price: 8, tab: 'seeds', unlock: 'unlock-fermentation', show: 'unlock-fermentation'},
    'buy-shovel': {id: 'buy-shovel', price: 10, tab: 'utility', unlock: 'start', show: 'start'},
    'buy-better-shovel': {id: 'buy-better-shovel', price: 30, tab: 'utility', unlock: 'unlock-better-tools', show: 'start'},
    'buy-pickaxe': {id: 'buy-pickaxe', price: 18, tab: 'utility', unlock: 'unlock-pickaxe', show: 'start'},
    'buy-better-pickaxe': {
        id: 'buy-better-pickaxe',
        price: 24,
        tab: 'utility',
        unlock: 'unlock-pickaxe',
        show: 'unlock-pickaxe',
    },
    'buy-bucket': {id: 'buy-bucket', price: 8, tab: 'utility', unlock: 'start', show: 'start'},
    'buy-bucket-large': {id: 'buy-bucket-large', price: 22, tab: 'utility', unlock: 'unlock-better-tools', show: 'start'},
    'buy-box': {id: 'buy-box', price: 6, tab: 'utility', unlock: 'start', show: 'start'},
    'buy-box-large': {id: 'buy-box-large', price: 18, tab: 'utility', unlock: 'unlock-large-box', show: 'start'},
    'buy-fertilizer': {id: 'buy-fertilizer', price: 18, tab: 'utility', unlock: 'start', show: 'start'},
    'buy-synth-fertilizer': {
        id: 'buy-synth-fertilizer',
        price: 15,
        tab: 'utility',
        unlock: 'unlock-fertilizer',
        show: 'unlock-fertilizer',
    },
    'buy-weed-spray': {
        id: 'buy-weed-spray',
        price: 12,
        tab: 'utility',
        unlock: 'unlock-fertilizer',
        show: 'unlock-fertilizer',
    },
    'buy-compost-box': {id: 'buy-compost-box', price: 20, tab: 'automation', unlock: 'unlock-compost', show: 'unlock-fertilizer'},
    'buy-pumpjack': {id: 'buy-pumpjack', price: 40, tab: 'automation', unlock: 'unlock-irrigation', show: 'start'},
    'buy-chest': {id: 'buy-chest', price: 18, tab: 'automation', unlock: 'unlock-chest', show: 'start'},
    'buy-grinder': {id: 'buy-grinder', price: 30, tab: 'automation', unlock: 'unlock-grinder', show: 'start'},
    'buy-pipe': {id: 'buy-pipe', price: 4, tab: 'automation', unlock: 'unlock-auto-irrigation', show: 'unlock-auto-irrigation'},
    'buy-sprinkler': {id: 'buy-sprinkler', price: 15, tab: 'automation', unlock: 'unlock-auto-irrigation', show: 'unlock-irrigation'},
    'buy-sprinkler-vert': {
        id: 'buy-sprinkler-vert',
        price: 30,
        tab: 'automation',
        unlock: 'unlock-adv-irrigation',
        show: 'unlock-auto-irrigation',
    },
    'buy-sprinkler-large': {
        id: 'buy-sprinkler-large',
        price: 33,
        tab: 'automation',
        unlock: 'unlock-adv-irrigation',
        show: 'unlock-auto-irrigation',
    },
    'buy-well': {id: 'buy-well', price: 75, tab: 'automation', unlock: 'unlock-adv-irrigation', show: 'unlock-auto-irrigation'},
    'buy-valve': {id: 'buy-valve', price: 6, tab: 'automation', unlock: 'unlock-auto-irrigation', show: 'unlock-auto-irrigation'},
    'buy-rain-tank': {id: 'buy-rain-tank', price: 20, tab: 'automation', unlock: 'unlock-auto-irrigation', show: 'unlock-irrigation'},
    'buy-tap': {id: 'buy-tap', price: 10, tab: 'automation', unlock: 'unlock-auto-irrigation', show: 'unlock-irrigation'},
    'buy-tile-cobble': {id: 'buy-tile-cobble', price: 5, tab: 'building', unlock: 'unlock-landscaping', show: 'start'},
    'buy-tile-brick': {id: 'buy-tile-brick', price: 7, tab: 'building', unlock: 'unlock-landscaping', show: 'start'},
    'buy-tile-paved': {id: 'buy-tile-paved', price: 11, tab: 'building', unlock: 'unlock-landscaping', show: 'start'},
    'buy-fence': {id: 'buy-fence', price: 10, tab: 'building', unlock: 'unlock-landscaping', show: 'start'},
    'pack-grass': {id: 'pack-grass', price: 1, tab: 'seeds', unlock: 'unlock-landscaping', show: 'start'},
    'buy-rotary-shovel': {
        id: 'buy-rotary-shovel',
        price: 1000,
        tab: 'utility',
        unlock: 'unlock-rotary-shovel',
        show: 'unlock-better-tools',
    },
    'buy-diamond-pickaxe': {
        id: 'buy-diamond-pickaxe',
        price: 1000,
        tab: 'utility',
        unlock: 'unlock-diamond-pickaxe',
        show: 'unlock-pickaxe',
    },
    'buy-mill': {id: 'buy-mill', price: 35, tab: 'automation', unlock: 'unlock-grinder', show: 'start'},
    'buy-jam': {id: 'buy-jam', price: 40, tab: 'automation', unlock: 'unlock-preservatives', show: 'unlock-grinder'},
    'buy-still': {id: 'buy-still', price: 45, tab: 'automation', unlock: 'unlock-fermentation', show: 'start'},
    'buy-barrel': {id: 'buy-barrel', price: 28, tab: 'automation', unlock: 'unlock-fermentation', show: 'start'},
    'buy-freezer': {id: 'buy-freezer', price: 36, tab: 'automation', unlock: 'unlock-preservatives', show: 'unlock-grinder'},
    'buy-sugar': {id: 'buy-sugar', price: 16, tab: 'utility', unlock: 'unlock-preservatives', show: 'unlock-grinder'},
    'buy-hangar': {id: 'buy-hangar', price: 80, tab: 'automation', unlock: 'unlock-vehicles', show: 'unlock-irrigation'},
    'buy-silo-seed': {id: 'buy-silo-seed', price: 70, tab: 'automation', unlock: 'unlock-vehicles', show: 'unlock-irrigation'},
    'buy-silo-spray': {id: 'buy-silo-spray', price: 70, tab: 'automation', unlock: 'unlock-vehicles', show: 'unlock-irrigation'},
    'buy-silo-produce': {id: 'buy-silo-produce', price: 70, tab: 'automation', unlock: 'unlock-vehicles', show: 'unlock-irrigation'},
}
