import {
    AND_PRICE,
    BUTTON_PRICE,
    COUNTER_PRICE,
    LAMP_PRICE,
    LEVER_PRICE,
    NOT_PRICE,
    OR_PRICE,
    PULSER_PRICE,
    SENSOR_DAY_PRICE,
    SENSOR_FERT_PRICE,
    SENSOR_HARVEST_PRICE,
    SENSOR_WATER_PRICE,
    SMART_VALVE_PRICE,
    VEHICLE_DETECTOR_PRICE,
    TRAFFIC_LIGHT_PRICE,
    WATER_SYSTEM_PRICE,
} from './items.ts'
import type {ResearchId, SkuId} from '../sim/ids.ts'

export type ResearchDef = {
    id: ResearchId
    name: string
    tree: 'plants' | 'land' | 'automation' | 'trade'
    cost: number
    seconds: number
    /** OR. Any one done reveals the card. `[]` is on the shelf from the start. */
    reveal: readonly ResearchId[]
    /** AND. Every one must be done before `startResearch` takes. */
    requires: readonly ResearchId[]
    grants: readonly string[]
    blurb: string
    effect:
        | { kind: 'unlock-sku'; sku: SkuId }
        | { kind: 'expand' }
        | { kind: 'feature' }
}

export const RESEARCH: { readonly [K in ResearchId]: ResearchDef } = {
    'unlock-fertilizer': {
        id: 'unlock-fertilizer',
        name: 'Synthetic fertilizer',
        tree: 'plants',
        cost: 10,
        seconds: 30,
        reveal: [],
        requires: [],
        grants: [],
        blurb: 'Unlocks Synthetic fertilizer in the general store. Instant, bought by the bag, and it ends organic.',
        effect: {kind: 'unlock-sku', sku: 'buy-synth-fertilizer'},
    },
    'unlock-compost': {
        id: 'unlock-compost',
        name: 'Composting',
        tree: 'plants',
        cost: 10,
        seconds: 30,
        reveal: [],
        requires: [],
        grants: [],
        blurb: 'Unlocks Compost box in the general store. Slow, fed by hand, and it keeps the soil organic.',
        effect: {kind: 'unlock-sku', sku: 'buy-compost-box'},
    },
    'unlock-tomato': {
        id: 'unlock-tomato',
        name: 'Tomato seeds',
        tree: 'plants',
        cost: 8,
        seconds: 30,
        reveal: [],
        requires: [],
        grants: [],
        blurb: 'Unlocks Tomato seeds in the general store.',
        effect: {kind: 'unlock-sku', sku: 'pack-tomato'},
    },
    'unlock-watermelon': {
        id: 'unlock-watermelon',
        name: 'Watermelon seeds',
        tree: 'plants',
        cost: 14,
        seconds: 45,
        reveal: [],
        requires: [],
        grants: [],
        blurb: 'Unlocks Watermelon seeds in the general store.',
        effect: {kind: 'unlock-sku', sku: 'pack-watermelon'},
    },
    'unlock-grape': {
        id: 'unlock-grape',
        name: 'Grape seeds',
        tree: 'plants',
        cost: 12,
        seconds: 40,
        reveal: ['unlock-tomato', 'unlock-watermelon'],
        requires: [],
        grants: [],
        blurb: 'Unlocks Grape seeds in the general store.',
        effect: {kind: 'unlock-sku', sku: 'pack-grape'},
    },
    'unlock-raspberry': {
        id: 'unlock-raspberry',
        name: 'Raspberry seeds',
        tree: 'plants',
        cost: 32,
        seconds: 45,
        reveal: ['unlock-tomato', 'unlock-watermelon', 'unlock-grape'],
        requires: [],
        grants: [],
        blurb: 'Unlocks Raspberry seeds in the general store. Sells high and rots fast.',
        effect: {kind: 'unlock-sku', sku: 'pack-raspberry'},
    },
    'unlock-heirloom': {
        id: 'unlock-heirloom',
        name: 'Heirloom crops',
        tree: 'plants',
        cost: 140,
        seconds: 140,
        reveal: ['expand-land', 'unlock-vehicles'],
        requires: [],
        grants: ['Heirloom rarity column in the store'],
        blurb: 'Unlocks Őstermelő. Heirloom produce can sell for more.',
        effect: {kind: 'feature'},
    },
    'unlock-expand': {
        id: 'unlock-expand',
        name: 'Unlock land',
        tree: 'land',
        cost: 25,
        seconds: 50,
        reveal: [],
        requires: [],
        grants: ['Land expansion on the map edge', '+1 expansion permit'],
        blurb: 'Unlocks land expansion on the map edge, and grants the first expansion permit.',
        effect: {kind: 'expand'},
    },
    'unlock-pickaxe': {
        id: 'unlock-pickaxe',
        name: 'Pickaxes',
        tree: 'land',
        cost: 12,
        seconds: 40,
        reveal: ['unlock-better-tools', 'unlock-expand'],
        requires: [],
        grants: [],
        blurb: 'Unlocks Pickaxe and Hardened pickaxe in the general store.',
        effect: {kind: 'unlock-sku', sku: 'buy-pickaxe'},
    },
    'expand-land': {
        id: 'expand-land',
        name: 'Expand land',
        tree: 'land',
        cost: 120,
        seconds: 110,
        reveal: ['unlock-expand'],
        requires: ['unlock-expand'],
        grants: ['+1 expansion permit'],
        blurb: 'A second expansion permit. Land still costs money on top of the permit.',
        effect: {kind: 'expand'},
    },
    'eminent-domain': {
        id: 'eminent-domain',
        name: 'Eminent domain',
        tree: 'land',
        cost: 420,
        seconds: 200,
        reveal: ['expand-land'],
        requires: ['expand-land'],
        grants: ['+1 expansion permit'],
        blurb: 'A third expansion permit. Further permits are contract work, not paperwork.',
        effect: {kind: 'expand'},
    },
    'unlock-landscaping': {
        id: 'unlock-landscaping',
        name: 'Landscape architecture',
        tree: 'land',
        cost: 12,
        seconds: 30,
        reveal: ['unlock-expand'],
        requires: [],
        grants: [],
        blurb: 'Unlocks Grass seeds, Wooden fence and every paving tile in the general store.',
        effect: {kind: 'unlock-sku', sku: 'pack-grass'},
    },
    'unlock-irrigation': {
        id: 'unlock-irrigation',
        name: 'Irrigation',
        tree: 'automation',
        cost: 12,
        seconds: 40,
        reveal: [],
        requires: [],
        grants: [],
        blurb: 'Unlocks Pipe and Tap in the general store. Route the water the farm pump already lifts.',
        effect: {kind: 'unlock-sku', sku: 'buy-pipe'},
    },
    'unlock-water-storage': {
        id: 'unlock-water-storage',
        name: 'Water storage',
        tree: 'automation',
        cost: 30,
        seconds: 70,
        reveal: ['unlock-irrigation'],
        requires: ['unlock-irrigation'],
        grants: [],
        blurb: 'Unlocks Well and Pumpjack in the general store. A second source, for when one pump runs short.',
        effect: {kind: 'unlock-sku', sku: 'buy-pumpjack'},
    },
    'unlock-auto-irrigation': {
        id: 'unlock-auto-irrigation',
        name: 'Automated irrigation',
        tree: 'automation',
        cost: 20,
        seconds: 55,
        reveal: ['unlock-irrigation'],
        requires: ['unlock-irrigation'],
        grants: [],
        blurb: 'Unlocks Sprinkler and Manual valve in the general store.',
        effect: {kind: 'unlock-sku', sku: 'buy-sprinkler'},
    },
    'unlock-adv-irrigation': {
        id: 'unlock-adv-irrigation',
        name: 'Advanced irrigation',
        tree: 'automation',
        cost: 75,
        seconds: 75,
        reveal: ['unlock-auto-irrigation'],
        requires: ['unlock-auto-irrigation'],
        grants: [],
        blurb: 'Unlocks Vertical sprinkler and Large sprinkler in the general store.',
        effect: {kind: 'unlock-sku', sku: 'buy-sprinkler-vert'},
    },
    'unlock-sensors': {
        id: 'unlock-sensors',
        name: 'Sensors',
        tree: 'automation',
        cost: 20,
        seconds: 50,
        reveal: [],
        requires: [],
        grants: ['Sensors lens row'],
        blurb: 'Unlocks the Sensors shelf: lever, button, lamp, pulser, counter, and field readers.',
        effect: {kind: 'feature'},
    },
    'unlock-advanced-sensors': {
        id: 'unlock-advanced-sensors',
        name: 'Advanced sensors',
        tree: 'automation',
        cost: 140,
        seconds: 60,
        reveal: ['unlock-sensors'],
        requires: ['unlock-sensors'],
        grants: [],
        blurb: 'Unlocks AND, OR, and NOT. AND is on if both inputs are. OR if either is. NOT inverts.',
        effect: {kind: 'feature'},
    },
    'unlock-smart-irrigation': {
        id: 'unlock-smart-irrigation',
        name: 'Smart irrigation',
        tree: 'automation',
        cost: 60,
        seconds: 100,
        reveal: ['unlock-sensors'],
        requires: ['unlock-adv-irrigation', 'unlock-sensors'],
        grants: ['Sprinkler crop dial', 'Sprinkler signal input', 'Signal wire endpoints on sprinklers'],
        blurb: 'Every sprinkler gains a crop dial and a signal input. Unlocks Smart valve.',
        effect: {kind: 'feature'},
    },
    'unlock-vehicles': {
        id: 'unlock-vehicles',
        name: 'Vehicles',
        tree: 'automation',
        cost: 40,
        seconds: 80,
        reveal: ['unlock-expand'],
        requires: [],
        grants: ['Quad, tractor and trailer at the hangar'],
        blurb: 'Unlocks Hangar. Buy Quads, tractors and trailers at a hangar.',
        effect: {kind: 'unlock-sku', sku: 'buy-hangar'},
    },
    'unlock-dispatch': {
        id: 'unlock-dispatch',
        name: 'Automated dispatch',
        tree: 'automation',
        cost: 35,
        seconds: 70,
        reveal: ['unlock-vehicles'],
        requires: ['unlock-vehicles'],
        grants: ['Automate chrome'],
        blurb: 'Vehicles follow a shared stop list; the traffic light holds a vehicle only if that light is a stop.',
        effect: {kind: 'feature'},
    },
    'unlock-silos': {
        id: 'unlock-silos',
        name: 'Field silos',
        tree: 'automation',
        cost: 30,
        seconds: 60,
        reveal: ['unlock-vehicles'],
        requires: ['unlock-vehicles'],
        grants: [],
        blurb: 'Unlocks Seed, Spray and Produce silo in the general store. Stock the field, not the house.',
        effect: {kind: 'unlock-sku', sku: 'buy-silo-seed'},
    },
    'unlock-contracts': {
        id: 'unlock-contracts',
        name: 'Contracts',
        tree: 'trade',
        cost: 10,
        seconds: 30,
        reveal: [],
        requires: [],
        grants: ['Contracts board at the stall', 'Reputation decay'],
        blurb: 'The stall can take orders from buyers.',
        effect: {kind: 'feature'},
    },
    'unlock-better-tools': {
        id: 'unlock-better-tools',
        name: 'Better gardening tools',
        tree: 'trade',
        cost: 16,
        seconds: 45,
        reveal: [],
        requires: [],
        grants: [],
        blurb: 'Unlocks Better shovel and Large bucket in the general store.',
        effect: {kind: 'unlock-sku', sku: 'buy-better-shovel'},
    },
    'unlock-large-box': {
        id: 'unlock-large-box',
        name: 'Fruit boxes',
        tree: 'trade',
        cost: 15,
        seconds: 40,
        reveal: [],
        requires: [],
        grants: [],
        blurb: 'Unlocks Large fruit box in the general store.',
        effect: {kind: 'unlock-sku', sku: 'buy-box-large'},
    },
    'unlock-chest': {
        id: 'unlock-chest',
        name: 'Chest',
        tree: 'trade',
        cost: 14,
        seconds: 40,
        reveal: ['unlock-large-box'],
        requires: [],
        grants: [],
        blurb: 'Unlocks Chest in the general store.',
        effect: {kind: 'unlock-sku', sku: 'buy-chest'},
    },
    'unlock-grinder': {
        id: 'unlock-grinder',
        name: 'Seed grinder',
        tree: 'trade',
        cost: 20,
        seconds: 50,
        reveal: [],
        requires: [],
        grants: [],
        blurb: 'Unlocks Seed grinder and Mill in the general store.',
        effect: {kind: 'unlock-sku', sku: 'buy-grinder'},
    },
    'unlock-preservatives': {
        id: 'unlock-preservatives',
        name: 'Preservatives',
        tree: 'trade',
        cost: 30,
        seconds: 70,
        reveal: ['unlock-grinder'],
        requires: ['unlock-grinder'],
        grants: ['Jam icon in the almanac'],
        blurb: 'Unlocks Jam machine, Freezer, and Sugar in the general store.',
        effect: {kind: 'unlock-sku', sku: 'buy-jam'},
    },
    'unlock-fermentation': {
        id: 'unlock-fermentation',
        name: 'Fermentation',
        tree: 'trade',
        cost: 45,
        seconds: 85,
        reveal: ['unlock-grinder'],
        requires: [],
        grants: [],
        blurb: 'Unlocks Sugar cane seeds, Pot still, and Wine barrel. Ripe cane is fruit. Mill cane for sugar.',
        effect: {kind: 'unlock-sku', sku: 'pack-sugar-cane'},
    },
}



export type SkuTab = 'seeds' | 'utility' | 'automation' | 'building'

/**
 * OR over the list: any one done satisfies it. `[]` is no second lock.
 * `'prize'`: not for sale. Stock arrives from contract prizes and is spent on placement.
 */
export type SkuNeed = readonly ResearchId[] | 'prize'

export type Sku = {
    id: SkuId
    price: number
    tab: SkuTab
    unlock: 'start' | ResearchId
    show: 'start' | ResearchId
    need: SkuNeed
}

export const SKUS: { readonly [K in SkuId]: Sku } = {
    'pack-carrot': {id: 'pack-carrot', price: 3, tab: 'seeds', unlock: 'start', show: 'start', need: []},
    'pack-potato': {id: 'pack-potato', price: 6, tab: 'seeds', unlock: 'start', show: 'start', need: []},
    'pack-wheat': {id: 'pack-wheat', price: 10, tab: 'seeds', unlock: 'start', show: 'start', need: []},
    'pack-tomato': {id: 'pack-tomato', price: 15, tab: 'seeds', unlock: 'unlock-tomato', show: 'start', need: []},
    'pack-watermelon': {id: 'pack-watermelon', price: 18, tab: 'seeds', unlock: 'unlock-watermelon', show: 'start', need: []},
    'pack-grape': {id: 'pack-grape', price: 16, tab: 'seeds', unlock: 'unlock-grape', show: 'start', need: []},
    'pack-raspberry': {id: 'pack-raspberry', price: 22, tab: 'seeds', unlock: 'unlock-raspberry', show: 'unlock-grape', need: []},
    'pack-sugar-cane': {id: 'pack-sugar-cane', price: 8, tab: 'seeds', unlock: 'unlock-fermentation', show: 'unlock-fermentation', need: []},
    'buy-shovel': {id: 'buy-shovel', price: 10, tab: 'utility', unlock: 'start', show: 'start', need: []},
    'buy-better-shovel': {id: 'buy-better-shovel', price: 30, tab: 'utility', unlock: 'unlock-better-tools', show: 'start', need: []},
    'buy-pickaxe': {id: 'buy-pickaxe', price: 18, tab: 'utility', unlock: 'unlock-pickaxe', show: 'start', need: []},
    'buy-better-pickaxe': {
        id: 'buy-better-pickaxe',
        price: 24,
        tab: 'utility',
        unlock: 'unlock-pickaxe',
        show: 'unlock-pickaxe',
        need: [],
    },
    'buy-bucket': {id: 'buy-bucket', price: 8, tab: 'utility', unlock: 'start', show: 'start', need: []},
    'buy-bucket-large': {id: 'buy-bucket-large', price: 22, tab: 'utility', unlock: 'unlock-better-tools', show: 'start', need: []},
    'buy-box': {id: 'buy-box', price: 6, tab: 'utility', unlock: 'start', show: 'start', need: []},
    'buy-box-large': {id: 'buy-box-large', price: 18, tab: 'utility', unlock: 'unlock-large-box', show: 'start', need: []},
    'buy-fertilizer': {id: 'buy-fertilizer', price: 18, tab: 'utility', unlock: 'start', show: 'start', need: []},
    'buy-synth-fertilizer': {
        id: 'buy-synth-fertilizer',
        price: 15,
        tab: 'utility',
        unlock: 'unlock-fertilizer',
        show: 'unlock-fertilizer',
        need: [],
    },
    'buy-weed-spray': {
        id: 'buy-weed-spray',
        price: 12,
        tab: 'utility',
        unlock: 'unlock-fertilizer',
        show: 'unlock-fertilizer',
        need: [],
    },
    'buy-compost-box': {id: 'buy-compost-box', price: 20, tab: 'automation', unlock: 'unlock-compost', show: 'start', need: []},
    'buy-pumpjack': {id: 'buy-pumpjack', price: 40, tab: 'automation', unlock: 'unlock-water-storage', show: 'start', need: []},
    'buy-chest': {id: 'buy-chest', price: 18, tab: 'automation', unlock: 'unlock-chest', show: 'start', need: []},
    'buy-grinder': {id: 'buy-grinder', price: 30, tab: 'automation', unlock: 'unlock-grinder', show: 'start', need: []},
    'buy-pipe': {id: 'buy-pipe', price: 4, tab: 'automation', unlock: 'unlock-irrigation', show: 'start', need: []},
    'buy-sprinkler': {id: 'buy-sprinkler', price: 15, tab: 'automation', unlock: 'unlock-auto-irrigation', show: 'unlock-irrigation', need: []},
    'buy-sprinkler-vert': {
        id: 'buy-sprinkler-vert',
        price: 30,
        tab: 'automation',
        unlock: 'unlock-adv-irrigation',
        show: 'unlock-auto-irrigation',
        need: [],
    },
    'buy-sprinkler-large': {
        id: 'buy-sprinkler-large',
        price: 33,
        tab: 'automation',
        unlock: 'unlock-adv-irrigation',
        show: 'unlock-auto-irrigation',
        need: [],
    },
    'buy-well': {id: 'buy-well', price: 75, tab: 'automation', unlock: 'unlock-water-storage', show: 'unlock-irrigation', need: []},
    'buy-valve': {id: 'buy-valve', price: 6, tab: 'automation', unlock: 'unlock-auto-irrigation', show: 'unlock-auto-irrigation', need: []},
    'buy-rain-tank': {id: 'buy-rain-tank', price: 20, tab: 'automation', unlock: 'start', show: 'start', need: []},
    'buy-tap': {id: 'buy-tap', price: 10, tab: 'automation', unlock: 'unlock-irrigation', show: 'start', need: []},
    'buy-tile-cobble': {id: 'buy-tile-cobble', price: 5, tab: 'building', unlock: 'unlock-landscaping', show: 'start', need: []},
    'buy-tile-brick': {id: 'buy-tile-brick', price: 7, tab: 'building', unlock: 'unlock-landscaping', show: 'start', need: []},
    'buy-tile-paved': {id: 'buy-tile-paved', price: 11, tab: 'building', unlock: 'unlock-landscaping', show: 'start', need: []},
    'buy-fence': {id: 'buy-fence', price: 10, tab: 'building', unlock: 'unlock-landscaping', show: 'start', need: []},
    'pack-grass': {id: 'pack-grass', price: 1, tab: 'seeds', unlock: 'unlock-landscaping', show: 'start', need: []},
    'buy-mill': {id: 'buy-mill', price: 35, tab: 'automation', unlock: 'unlock-grinder', show: 'start', need: []},
    'buy-jam': {id: 'buy-jam', price: 40, tab: 'automation', unlock: 'unlock-preservatives', show: 'unlock-grinder', need: []},
    'buy-still': {id: 'buy-still', price: 45, tab: 'automation', unlock: 'unlock-fermentation', show: 'start', need: []},
    'buy-barrel': {id: 'buy-barrel', price: 28, tab: 'automation', unlock: 'unlock-fermentation', show: 'start', need: []},
    'buy-freezer': {id: 'buy-freezer', price: 36, tab: 'automation', unlock: 'unlock-preservatives', show: 'unlock-grinder', need: []},
    'buy-freezer-large': {id: 'buy-freezer-large', price: 0, tab: 'automation', unlock: 'start', show: 'start', need: 'prize'},
    'buy-sugar': {id: 'buy-sugar', price: 16, tab: 'utility', unlock: 'unlock-preservatives', show: 'unlock-grinder', need: []},
    'buy-hangar': {id: 'buy-hangar', price: 80, tab: 'automation', unlock: 'unlock-vehicles', show: 'unlock-irrigation', need: []},
    'buy-silo-seed': {id: 'buy-silo-seed', price: 70, tab: 'automation', unlock: 'unlock-silos', show: 'unlock-vehicles', need: []},
    'buy-silo-spray': {id: 'buy-silo-spray', price: 70, tab: 'automation', unlock: 'unlock-silos', show: 'unlock-vehicles', need: []},
    'buy-silo-produce': {id: 'buy-silo-produce', price: 70, tab: 'automation', unlock: 'unlock-silos', show: 'unlock-vehicles', need: []},
    'buy-lever': {id: 'buy-lever', price: LEVER_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: []},
    'buy-button': {id: 'buy-button', price: BUTTON_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: []},
    'buy-lamp': {id: 'buy-lamp', price: LAMP_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: []},
    'buy-or': {id: 'buy-or', price: OR_PRICE, tab: 'automation', unlock: 'unlock-advanced-sensors', show: 'unlock-sensors', need: []},
    'buy-and': {id: 'buy-and', price: AND_PRICE, tab: 'automation', unlock: 'unlock-advanced-sensors', show: 'unlock-sensors', need: []},
    'buy-not': {id: 'buy-not', price: NOT_PRICE, tab: 'automation', unlock: 'unlock-advanced-sensors', show: 'unlock-sensors', need: []},
    'buy-pulser': {id: 'buy-pulser', price: PULSER_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: []},
    'buy-counter': {id: 'buy-counter', price: COUNTER_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: []},
    'buy-sensor-water': {id: 'buy-sensor-water', price: SENSOR_WATER_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: ['unlock-irrigation']},
    'buy-sensor-fert': {id: 'buy-sensor-fert', price: SENSOR_FERT_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: ['unlock-fertilizer', 'unlock-compost']},
    'buy-sensor-harvest': {id: 'buy-sensor-harvest', price: SENSOR_HARVEST_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: []},
    'buy-sensor-day': {id: 'buy-sensor-day', price: SENSOR_DAY_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: []},
    'buy-water-system': {id: 'buy-water-system', price: WATER_SYSTEM_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: ['unlock-adv-irrigation']},
    'buy-smart-valve': {
        id: 'buy-smart-valve',
        price: SMART_VALVE_PRICE,
        tab: 'automation',
        unlock: 'unlock-smart-irrigation',
        show: 'unlock-sensors',
        need: [],
    },
    'buy-vehicle-detector': {
        id: 'buy-vehicle-detector',
        price: VEHICLE_DETECTOR_PRICE,
        tab: 'automation',
        unlock: 'unlock-sensors',
        show: 'unlock-sensors',
        need: ['unlock-vehicles'],
    },
    'buy-traffic-light': {
        id: 'buy-traffic-light',
        price: TRAFFIC_LIGHT_PRICE,
        tab: 'automation',
        unlock: 'unlock-sensors',
        show: 'unlock-sensors',
        need: ['unlock-dispatch'],
    },
}
