import { m } from '../../paraglide/messages.js'
import {
    AND_PRICE,
    BUTTON_PRICE,
    COUNTER_PRICE,
    LAMP_PRICE,
    LEVER_PRICE,
    NOT_PRICE,
    OR_PRICE,
    PULSER_PRICE,
    SENSOR_DAY_PRICE,
    SENSOR_FERT_PRICE,
    SENSOR_HARVEST_PRICE,
    SENSOR_WATER_PRICE,
    VEHICLE_DETECTOR_PRICE,
    TRAFFIC_LIGHT_PRICE,
    WATER_SYSTEM_PRICE,
} from './items.ts'
import type {ResearchId, SkuId} from '../sim/ids.ts'

export type ResearchDef = {
    id: ResearchId
    name: string
    tree: 'plants' | 'land' | 'automation' | 'trade'
    cost: number
    seconds: number
    /** OR. Any one done reveals the card. `[]` is on the shelf from the start. */
    reveal: readonly ResearchId[]
    /** AND. Every one must be done before `startResearch` takes. */
    requires: readonly ResearchId[]
    grants: readonly string[]
    blurb: string
    effect:
        | { kind: 'unlock-sku'; sku: SkuId }
        | { kind: 'expand' }
        | { kind: 'feature' }
}

export const RESEARCH: { readonly [K in ResearchId]: ResearchDef } = {
    'unlock-fertilizer': {
        id: 'unlock-fertilizer',
        name: m.research_unlock_fertilizer_name(),
        tree: 'plants',
        cost: 10,
        seconds: 30,
        reveal: [],
        requires: [],
        grants: [],
        blurb: m.research_unlock_fertilizer_blurb(),
        effect: {kind: 'unlock-sku', sku: 'buy-synth-fertilizer'},
    },
    'unlock-tomato': {
        id: 'unlock-tomato',
        name: m.research_unlock_tomato_name(),
        tree: 'plants',
        cost: 8,
        seconds: 30,
        reveal: [],
        requires: [],
        grants: [],
        blurb: m.research_unlock_tomato_blurb(),
        effect: {kind: 'unlock-sku', sku: 'pack-tomato'},
    },
    'unlock-grape': {
        id: 'unlock-grape',
        name: m.research_unlock_grape_name(),
        tree: 'plants',
        cost: 12,
        seconds: 40,
        reveal: [],
        requires: [],
        grants: [],
        blurb: m.research_unlock_grape_blurb(),
        effect: {kind: 'unlock-sku', sku: 'pack-grape'},
    },
    'unlock-raspberry': {
        id: 'unlock-raspberry',
        name: m.research_unlock_raspberry_name(),
        tree: 'plants',
        cost: 32,
        seconds: 45,
        reveal: ['unlock-tomato', 'unlock-grape'],
        requires: [],
        grants: [],
        blurb: m.research_unlock_raspberry_blurb(),
        effect: {kind: 'unlock-sku', sku: 'pack-raspberry'},
    },
    'unlock-crop-variants': {
        id: 'unlock-crop-variants',
        name: m.research_unlock_crop_variants_name(),
        tree: 'plants',
        cost: 5,
        seconds: 40,
        reveal: ['unlock-tomato', 'unlock-grape', 'unlock-irrigation'],
        requires: [],
        grants: [m.research_grant_rarity_rolls(), m.research_grant_silo_rows()],
        blurb: m.research_unlock_crop_variants_blurb(),
        effect: {kind: 'feature'},
    },
    'unlock-heirloom': {
        id: 'unlock-heirloom',
        name: m.research_unlock_heirloom_name(),
        tree: 'plants',
        cost: 140,
        seconds: 140,
        reveal: ['expand-land', 'unlock-vehicles', 'unlock-crop-variants'],
        requires: ['unlock-crop-variants'],
        grants: [m.research_grant_heirloom_column()],
        blurb: m.research_unlock_heirloom_blurb(),
        effect: {kind: 'feature'},
    },
    'unlock-expand': {
        id: 'unlock-expand',
        name: m.research_unlock_expand_name(),
        tree: 'land',
        cost: 25,
        seconds: 45,
        reveal: [],
        requires: [],
        grants: [m.research_grant_land_edge(), m.research_grant_permit()],
        blurb: m.research_unlock_expand_blurb(),
        effect: {kind: 'expand'},
    },
    'unlock-pickaxe': {
        id: 'unlock-pickaxe',
        name: m.research_unlock_pickaxe_name(),
        tree: 'land',
        cost: 12,
        seconds: 40,
        reveal: ['unlock-better-tools', 'unlock-expand'],
        requires: [],
        grants: [],
        blurb: m.research_unlock_pickaxe_blurb(),
        effect: {kind: 'unlock-sku', sku: 'buy-pickaxe'},
    },
    'expand-land': {
        id: 'expand-land',
        name: m.research_expand_land_name(),
        tree: 'land',
        cost: 120,
        seconds: 90,
        reveal: ['unlock-expand'],
        requires: ['unlock-expand'],
        grants: [m.research_grant_permit()],
        blurb: m.research_expand_land_blurb(),
        effect: {kind: 'expand'},
    },
    'eminent-domain': {
        id: 'eminent-domain',
        name: m.research_eminent_domain_name(),
        tree: 'land',
        cost: 420,
        seconds: 180,
        reveal: ['expand-land'],
        requires: ['expand-land'],
        grants: [m.research_grant_permit()],
        blurb: m.research_eminent_domain_blurb(),
        effect: {kind: 'expand'},
    },
    'unlock-landscaping': {
        id: 'unlock-landscaping',
        name: m.research_unlock_landscaping_name(),
        tree: 'land',
        cost: 12,
        seconds: 30,
        reveal: ['unlock-expand'],
        requires: [],
        grants: [],
        blurb: m.research_unlock_landscaping_blurb(),
        effect: {kind: 'unlock-sku', sku: 'pack-grass'},
    },
    'unlock-irrigation': {
        id: 'unlock-irrigation',
        name: m.research_unlock_irrigation_name(),
        tree: 'automation',
        cost: 10,
        seconds: 40,
        reveal: [],
        requires: [],
        grants: [],
        blurb: m.research_unlock_irrigation_blurb(),
        effect: {kind: 'unlock-sku', sku: 'buy-pipe'},
    },
    'unlock-water-storage': {
        id: 'unlock-water-storage',
        name: m.research_unlock_water_storage_name(),
        tree: 'automation',
        cost: 30,
        seconds: 70,
        reveal: ['unlock-irrigation'],
        requires: ['unlock-irrigation'],
        grants: [],
        blurb: m.research_unlock_water_storage_blurb(),
        effect: {kind: 'unlock-sku', sku: 'buy-pumpjack'},
    },
    'unlock-auto-irrigation': {
        id: 'unlock-auto-irrigation',
        name: m.research_unlock_auto_irrigation_name(),
        tree: 'automation',
        cost: 20,
        seconds: 55,
        reveal: ['unlock-irrigation'],
        requires: ['unlock-irrigation'],
        grants: [],
        blurb: m.research_unlock_auto_irrigation_blurb(),
        effect: {kind: 'unlock-sku', sku: 'buy-sprinkler'},
    },
    'unlock-adv-irrigation': {
        id: 'unlock-adv-irrigation',
        name: m.research_unlock_adv_irrigation_name(),
        tree: 'automation',
        cost: 75,
        seconds: 75,
        reveal: ['unlock-auto-irrigation'],
        requires: ['unlock-auto-irrigation'],
        grants: [],
        blurb: m.research_unlock_adv_irrigation_blurb(),
        effect: {kind: 'unlock-sku', sku: 'buy-sprinkler-vert'},
    },
    'unlock-sensors': {
        id: 'unlock-sensors',
        name: m.research_unlock_sensors_name(),
        tree: 'automation',
        cost: 20,
        seconds: 50,
        reveal: [],
        requires: [],
        grants: [m.research_grant_sensors_lens()],
        blurb: m.research_unlock_sensors_blurb(),
        effect: {kind: 'feature'},
    },
    'unlock-advanced-sensors': {
        id: 'unlock-advanced-sensors',
        name: m.research_unlock_advanced_sensors_name(),
        tree: 'automation',
        cost: 140,
        seconds: 60,
        reveal: ['unlock-sensors'],
        requires: ['unlock-sensors'],
        grants: [],
        blurb: m.research_unlock_advanced_sensors_blurb(),
        effect: {kind: 'feature'},
    },
    'unlock-smart-irrigation': {
        id: 'unlock-smart-irrigation',
        name: m.research_unlock_smart_irrigation_name(),
        tree: 'automation',
        cost: 60,
        seconds: 100,
        reveal: ['unlock-sensors'],
        requires: ['unlock-adv-irrigation', 'unlock-sensors'],
        grants: [m.research_grant_sprinkler_dial(), m.research_grant_sprinkler_signal(), m.research_grant_sprinkler_wire()],
        blurb: m.research_unlock_smart_irrigation_blurb(),
        effect: {kind: 'feature'},
    },
    'unlock-vehicles': {
        id: 'unlock-vehicles',
        name: m.research_unlock_vehicles_name(),
        tree: 'automation',
        cost: 50,
        seconds: 80,
        reveal: ['unlock-expand'],
        requires: [],
        grants: [m.research_grant_hangar_stock()],
        blurb: m.research_unlock_vehicles_blurb(),
        effect: {kind: 'unlock-sku', sku: 'buy-hangar'},
    },
    'unlock-dispatch': {
        id: 'unlock-dispatch',
        name: m.research_unlock_dispatch_name(),
        tree: 'automation',
        cost: 100,
        seconds: 80,
        reveal: ['unlock-vehicles'],
        requires: ['unlock-vehicles'],
        grants: [m.research_grant_automate()],
        blurb: m.research_unlock_dispatch_blurb(),
        effect: {kind: 'feature'},
    },
    'unlock-silos': {
        id: 'unlock-silos',
        name: m.research_unlock_silos_name(),
        tree: 'automation',
        cost: 30,
        seconds: 60,
        reveal: ['unlock-vehicles'],
        requires: ['unlock-vehicles'],
        grants: [],
        blurb: m.research_unlock_silos_blurb(),
        effect: {kind: 'unlock-sku', sku: 'buy-silo-seed'},
    },
    'unlock-contracts': {
        id: 'unlock-contracts',
        name: m.research_unlock_contracts_name(),
        tree: 'trade',
        cost: 10,
        seconds: 30,
        reveal: [],
        requires: [],
        grants: [m.research_grant_contracts_board(), m.research_grant_rep_decay()],
        blurb: m.research_unlock_contracts_blurb(),
        effect: {kind: 'feature'},
    },
    'unlock-better-tools': {
        id: 'unlock-better-tools',
        name: m.research_unlock_better_tools_name(),
        tree: 'trade',
        cost: 16,
        seconds: 45,
        reveal: [],
        requires: [],
        grants: [],
        blurb: m.research_unlock_better_tools_blurb(),
        effect: {kind: 'unlock-sku', sku: 'buy-better-shovel'},
    },
    'unlock-chest': {
        id: 'unlock-chest',
        name: m.research_unlock_chest_name(),
        tree: 'trade',
        cost: 10,
        seconds: 40,
        reveal: [],
        requires: [],
        grants: [],
        blurb: m.research_unlock_chest_blurb(),
        effect: {kind: 'unlock-sku', sku: 'buy-chest'},
    },
    'unlock-grinder': {
        id: 'unlock-grinder',
        name: m.research_unlock_grinder_name(),
        tree: 'trade',
        cost: 10,
        seconds: 50,
        reveal: [],
        requires: [],
        grants: [],
        blurb: m.research_unlock_grinder_blurb(),
        effect: {kind: 'unlock-sku', sku: 'buy-grinder'},
    },
    'unlock-preservatives': {
        id: 'unlock-preservatives',
        name: m.research_unlock_preservatives_name(),
        tree: 'trade',
        cost: 30,
        seconds: 70,
        reveal: ['unlock-grinder'],
        requires: ['unlock-grinder'],
        grants: [m.research_grant_jam_almanac()],
        blurb: m.research_unlock_preservatives_blurb(),
        effect: {kind: 'unlock-sku', sku: 'buy-jam'},
    },
    'unlock-fermentation': {
        id: 'unlock-fermentation',
        name: m.research_unlock_fermentation_name(),
        tree: 'trade',
        cost: 45,
        seconds: 85,
        reveal: ['unlock-grinder'],
        requires: [],
        grants: [],
        blurb: m.research_unlock_fermentation_blurb(),
        effect: {kind: 'unlock-sku', sku: 'pack-sugar-cane'},
    },
}



export type SkuTab = 'seeds' | 'utility' | 'automation' | 'building'

/**
 * OR over the list: any one done satisfies it. `[]` is no second lock.
 * `'prize'`: not for sale. Stock arrives from contract prizes and is spent on placement.
 */
export type SkuNeed = readonly ResearchId[] | 'prize'

export type Sku = {
    id: SkuId
    price: number
    tab: SkuTab
    unlock: 'start' | ResearchId
    show: 'start' | ResearchId
    need: SkuNeed
}

export const SKUS: { readonly [K in SkuId]: Sku } = {
    'pack-carrot': {id: 'pack-carrot', price: 3, tab: 'seeds', unlock: 'start', show: 'start', need: []},
    'pack-potato': {id: 'pack-potato', price: 6, tab: 'seeds', unlock: 'start', show: 'start', need: []},
    'pack-wheat': {id: 'pack-wheat', price: 10, tab: 'seeds', unlock: 'start', show: 'start', need: []},
    'pack-tomato': {id: 'pack-tomato', price: 15, tab: 'seeds', unlock: 'unlock-tomato', show: 'start', need: []},
    'pack-grape': {id: 'pack-grape', price: 16, tab: 'seeds', unlock: 'unlock-grape', show: 'start', need: []},
    'pack-raspberry': {id: 'pack-raspberry', price: 22, tab: 'seeds', unlock: 'unlock-raspberry', show: 'unlock-grape', need: []},
    'pack-sugar-cane': {id: 'pack-sugar-cane', price: 8, tab: 'seeds', unlock: 'unlock-fermentation', show: 'unlock-fermentation', need: []},
    'buy-shovel': {id: 'buy-shovel', price: 10, tab: 'utility', unlock: 'start', show: 'start', need: []},
    'buy-better-shovel': {id: 'buy-better-shovel', price: 30, tab: 'utility', unlock: 'unlock-better-tools', show: 'start', need: []},
    'buy-pickaxe': {id: 'buy-pickaxe', price: 18, tab: 'utility', unlock: 'unlock-pickaxe', show: 'start', need: []},
    'buy-better-pickaxe': {
        id: 'buy-better-pickaxe',
        price: 24,
        tab: 'utility',
        unlock: 'unlock-pickaxe',
        show: 'unlock-pickaxe',
        need: [],
    },
    'buy-bucket': {id: 'buy-bucket', price: 8, tab: 'utility', unlock: 'start', show: 'start', need: []},
    'buy-bucket-large': {id: 'buy-bucket-large', price: 22, tab: 'utility', unlock: 'unlock-better-tools', show: 'start', need: []},
    'buy-fertilizer': {id: 'buy-fertilizer', price: 18, tab: 'utility', unlock: 'start', show: 'start', need: []},
    'buy-synth-fertilizer': {
        id: 'buy-synth-fertilizer',
        price: 15,
        tab: 'utility',
        unlock: 'unlock-fertilizer',
        show: 'unlock-fertilizer',
        need: [],
    },
    'buy-weed-spray': {
        id: 'buy-weed-spray',
        price: 12,
        tab: 'utility',
        unlock: 'unlock-fertilizer',
        show: 'unlock-fertilizer',
        need: [],
    },
    'buy-compost-box': {id: 'buy-compost-box', price: 8, tab: 'automation', unlock: 'start', show: 'start', need: []},
    'buy-pumpjack': {id: 'buy-pumpjack', price: 50, tab: 'automation', unlock: 'unlock-water-storage', show: 'start', need: []},
    'buy-chest': {id: 'buy-chest', price: 18, tab: 'automation', unlock: 'unlock-chest', show: 'start', need: []},
    'buy-grinder': {id: 'buy-grinder', price: 30, tab: 'automation', unlock: 'unlock-grinder', show: 'start', need: []},
    'buy-pipe': {id: 'buy-pipe', price: 3, tab: 'automation', unlock: 'unlock-irrigation', show: 'start', need: []},
    'buy-sprinkler': {id: 'buy-sprinkler', price: 16, tab: 'automation', unlock: 'unlock-auto-irrigation', show: 'unlock-irrigation', need: []},
    'buy-sprinkler-vert': {
        id: 'buy-sprinkler-vert',
        price: 30,
        tab: 'automation',
        unlock: 'unlock-adv-irrigation',
        show: 'unlock-auto-irrigation',
        need: [],
    },
    'buy-sprinkler-large': {
        id: 'buy-sprinkler-large',
        price: 48,
        tab: 'automation',
        unlock: 'unlock-adv-irrigation',
        show: 'unlock-auto-irrigation',
        need: [],
    },
    'buy-well': {id: 'buy-well', price: 75, tab: 'automation', unlock: 'unlock-water-storage', show: 'unlock-irrigation', need: []},
    'buy-valve': {id: 'buy-valve', price: 5, tab: 'automation', unlock: 'unlock-auto-irrigation', show: 'unlock-auto-irrigation', need: []},
    'buy-rain-tank': {id: 'buy-rain-tank', price: 25, tab: 'automation', unlock: 'start', show: 'start', need: []},
    'buy-tap': {id: 'buy-tap', price: 10, tab: 'automation', unlock: 'unlock-irrigation', show: 'start', need: []},
    'buy-tile-cobble': {id: 'buy-tile-cobble', price: 5, tab: 'building', unlock: 'unlock-landscaping', show: 'start', need: []},
    'buy-tile-brick': {id: 'buy-tile-brick', price: 7, tab: 'building', unlock: 'unlock-landscaping', show: 'start', need: []},
    'buy-tile-paved': {id: 'buy-tile-paved', price: 11, tab: 'building', unlock: 'unlock-landscaping', show: 'start', need: []},
    'buy-fence': {id: 'buy-fence', price: 8, tab: 'building', unlock: 'unlock-landscaping', show: 'start', need: []},
    'pack-grass': {id: 'pack-grass', price: 1, tab: 'seeds', unlock: 'unlock-landscaping', show: 'start', need: []},
    'buy-mill': {id: 'buy-mill', price: 45, tab: 'automation', unlock: 'unlock-grinder', show: 'start', need: []},
    'buy-jam': {id: 'buy-jam', price: 45, tab: 'automation', unlock: 'unlock-preservatives', show: 'unlock-grinder', need: []},
    'buy-still': {id: 'buy-still', price: 45, tab: 'automation', unlock: 'unlock-fermentation', show: 'start', need: []},
    'buy-barrel': {id: 'buy-barrel', price: 18, tab: 'automation', unlock: 'unlock-fermentation', show: 'start', need: []},
    'buy-freezer': {id: 'buy-freezer', price: 36, tab: 'automation', unlock: 'unlock-preservatives', show: 'unlock-grinder', need: []},
    'buy-freezer-large': {id: 'buy-freezer-large', price: 0, tab: 'automation', unlock: 'start', show: 'start', need: 'prize'},
    'buy-sugar': {id: 'buy-sugar', price: 16, tab: 'utility', unlock: 'unlock-preservatives', show: 'unlock-grinder', need: []},
    'buy-hangar': {id: 'buy-hangar', price: 80, tab: 'automation', unlock: 'unlock-vehicles', show: 'unlock-irrigation', need: []},
    'buy-silo-seed': {id: 'buy-silo-seed', price: 70, tab: 'automation', unlock: 'unlock-silos', show: 'unlock-vehicles', need: []},
    'buy-silo-spray': {id: 'buy-silo-spray', price: 70, tab: 'automation', unlock: 'unlock-silos', show: 'unlock-vehicles', need: []},
    'buy-silo-produce': {id: 'buy-silo-produce', price: 70, tab: 'automation', unlock: 'unlock-silos', show: 'unlock-vehicles', need: []},
    'buy-lever': {id: 'buy-lever', price: LEVER_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: []},
    'buy-button': {id: 'buy-button', price: BUTTON_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: []},
    'buy-lamp': {id: 'buy-lamp', price: LAMP_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: []},
    'buy-or': {id: 'buy-or', price: OR_PRICE, tab: 'automation', unlock: 'unlock-advanced-sensors', show: 'unlock-sensors', need: []},
    'buy-and': {id: 'buy-and', price: AND_PRICE, tab: 'automation', unlock: 'unlock-advanced-sensors', show: 'unlock-sensors', need: []},
    'buy-not': {id: 'buy-not', price: NOT_PRICE, tab: 'automation', unlock: 'unlock-advanced-sensors', show: 'unlock-sensors', need: []},
    'buy-pulser': {id: 'buy-pulser', price: PULSER_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: []},
    'buy-counter': {id: 'buy-counter', price: COUNTER_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: []},
    'buy-sensor-water': {id: 'buy-sensor-water', price: SENSOR_WATER_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: ['unlock-irrigation']},
    'buy-sensor-fert': {id: 'buy-sensor-fert', price: SENSOR_FERT_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: ['unlock-fertilizer']},
    'buy-sensor-harvest': {id: 'buy-sensor-harvest', price: SENSOR_HARVEST_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: []},
    'buy-sensor-day': {id: 'buy-sensor-day', price: SENSOR_DAY_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: []},
    'buy-water-system': {id: 'buy-water-system', price: WATER_SYSTEM_PRICE, tab: 'automation', unlock: 'unlock-sensors', show: 'unlock-sensors', need: ['unlock-adv-irrigation']},
    'buy-vehicle-detector': {
        id: 'buy-vehicle-detector',
        price: VEHICLE_DETECTOR_PRICE,
        tab: 'automation',
        unlock: 'unlock-sensors',
        show: 'unlock-sensors',
        need: ['unlock-vehicles'],
    },
    'buy-traffic-light': {
        id: 'buy-traffic-light',
        price: TRAFFIC_LIGHT_PRICE,
        tab: 'automation',
        unlock: 'unlock-sensors',
        show: 'unlock-sensors',
        need: ['unlock-dispatch'],
    },
}
